modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hexresearch"
version = "${version}"
displayName = "Hex Research"
logoFile = "hex_research.png"
authors = "Dashkal"
description = '''
An addon to Hex Casting that provides alternative ways to accomplish Hexcasting progression.
'''
displayURL = "https://dashkal16.github.io/HexResearch/v/latest/main/en_us"

[[dependencies.hexresearch]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexresearch]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexresearch]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexresearch]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.10.3,)"
ordering = "NONE"
side = "BOTH"
