modid = "hexresearch"
book = "hexresearch:hexresearchbook"
default_lang = "en_us"
default_branch = "develop"

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    { path="{^_common.src}/generated/resources", required=false },
    "{_fabric.src}/main/resources",
    { path="{^_fabric.src}/generated/resources", required=false },
    "{_forge.src}/main/resources",
    { path="{^_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexresearch/_export/generated"

[template]
icon = "icon.png"
include = [
    "hexresearch",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hex Research"
author = "Dashkal"
show_landing_text = false

[extra.hexcasting]
# regexes for parsing pattern registry files - try running copier update and picking a different regex if your patterns aren't loading
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='(?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?' }
_per_world_value = "registerPerWorld"

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/registry/HRHexPatterns.java"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../common/src"
package = "{src}/main/java/name/dashkal/minecraft/hexresearch"

[_fabric]
src = "../fabric/src"
package = "{src}/main/java/name/dashkal/minecraft/hexresearch/fabric"

[_forge]
src = "../forge/src"
package = "{src}/main/java/name/dashkal/minecraft/hexresearch/forge"
