name: Build and Test Hex Research

on:
  push:
    branches: [ $default-branch ]
    tags: "v*"
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      release:
        description: Release this version
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      modVersion: ${{ steps.modVersion.outputs.modVersion }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Set up Gradle 8.1
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1
    - name: Get Mod Version
      id: modVersion
      run: cat gradle.properties | grep modVersion >> "$GITHUB_OUTPUT"
    - name: Build
      run: gradle build
    - name: Test
      run: gradle test
    - name : Archive Forge
      uses: actions/upload-artifact@v4
      with:
        name: forge
        path: forge/build/libs/*.jar
        retention-days: 7
    - name : Archive Fabric
      uses: actions/upload-artifact@v4
      with:
        name: fabric
        path: fabric/build/libs/*.jar
        retention-days: 7
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: |-
      ${{
        github.event_name == 'workflow_dispatch' && inputs.release
        || (false && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
      }}
    environment: publish_mod
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: build/libs
        merge-multiple: true
    - uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ vars.MODRINTH_PROJECT_ID }}
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        dependencies: |
          hexcasting@(required){modrinth:nTW3yKrm}
          hexgloop@(optional){modrinth:ryfyOhoP}
