name: Build

on:
  push:
    branches: main
    # branches: ${{ github.event.repository.default_branch }}
    tags: "v*"
  pull_request:
    branches: main
    # branches: ${{ github.event.repository.default_branch }}
  workflow_dispatch:
#    inputs:
#      release:
#        description: Release this version
#        type: boolean
#        default: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      minecraftVersion: ${{ steps.versions.outputs.minecraftVersion }}
      modVersion: ${{ steps.versions.outputs.modVersion }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Set up Gradle 8.1
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1
    - name: Get Versions
      id: versions
      run: |
        cat gradle.properties | grep minecraftVersion >> "$GITHUB_OUTPUT"
        cat gradle.properties | grep modVersion >> "$GITHUB_OUTPUT"
    - name: Build
      run: gradle build
    - name: Test
      run: gradle test
    - name : Archive Forge
      uses: actions/upload-artifact@v4
      with:
        name: forge
        path: forge/build/libs/*.jar
        retention-days: 7
    - name : Archive Fabric
      uses: actions/upload-artifact@v4
      with:
        name: fabric
        path: fabric/build/libs/*.jar
        retention-days: 7
