name: Build and Test Hex Research

on:
  push:
    branches: [ $default-branch ]
    tags: "v*"
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Set up Gradle 8.1
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1
    - name: Build
      run: gradle build
    - name: Test
      run: gradle test
    - name : Archive Forge
      uses: actions/upload-artifact@v4
      with:
        name: forge
        path: forge/build/libs/*.jar
        retention-days: 7
    - name : Archive Fabric
      uses: actions/upload-artifact@v4
      with:
        name: fabric
        path: fabric/build/libs/*.jar
        retention-days: 7
